/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.craftcode.ap.java21Lab;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    //private static final Java21Collections collect = new Java21Collections();

    public static void main(String[] args) {

    }
}
